apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yml --volumes hostPath -o otel-k8s-manifests/
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: otelcol
  name: otelcol
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: otelcol
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-resolved.yml --volumes hostPath -o otel-k8s-manifests/
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/opentelemetry-demo: "true"
        io.kompose.service: otelcol
    spec:
      containers:
        - args:
            - --config=/etc/otelcol-config.yml
            - --config=/etc/otelcol-config-extras.yml
          image: otel/opentelemetry-collector-contrib:0.70.0
          name: otel-col
          ports:
            - containerPort: 4317
            - containerPort: 4318
            - containerPort: 9464
            - containerPort: 8888
          resources:
            limits:
              memory: "131072e3"
          volumeMounts:
            - mountPath: /etc/otelcol-config.yml
              name: otelcol-hostpath0
            - mountPath: /etc/otelcol-config-extras.yml
              name: otelcol-hostpath1
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /home/anthony/tigera/opentelemetry-demo/opentelemetry-demo/src/otelcollector/otelcol-config.yml
          name: otelcol-hostpath0
        - hostPath:
            path: /home/anthony/tigera/opentelemetry-demo/opentelemetry-demo/src/otelcollector/otelcol-config-extras.yml
          name: otelcol-hostpath1
status: {}
