apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yml -o otel-k8s-manifests/
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: quoteservice
  name: quoteservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: quoteservice
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-resolved.yml -o otel-k8s-manifests/
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/opentelemetry-demo: "true"
        io.kompose.service: quoteservice
    spec:
      containers:
        - env:
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: http://otelcol:4318/v1/traces
            - name: OTEL_PHP_AUTOLOAD_ENABLED
              value: "true"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.namespace=opentelemetry-demo
            - name: OTEL_SERVICE_NAME
              value: quoteservice
            - name: QUOTE_SERVICE_PORT
              value: "8090"
          image: ghcr.io/open-telemetry/demo:1.3.1-quoteservice
          name: quote-service
          ports:
            - containerPort: 8090
          resources:
            limits:
              memory: "41943040"
      restartPolicy: Always
status: {}
