apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yml --volumes=configMap -o otel-k8s-manifests/
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: shippingservice
  name: shippingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: shippingservice
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-resolved.yml --volumes=configMap -o otel-k8s-manifests/
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/opentelemetry-demo: "true"
        io.kompose.service: shippingservice
    spec:
      containers:
        - env:
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: http://otelcol:4317
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.namespace=opentelemetry-demo
            - name: OTEL_SERVICE_NAME
              value: shippingservice
            - name: QUOTE_SERVICE_ADDR
              value: http://quoteservice:8090
            - name: SHIPPING_SERVICE_PORT
              value: "50050"
          image: ghcr.io/open-telemetry/demo:1.3.1-shippingservice
          name: shipping-service
          ports:
            - containerPort: 50050
          resources:
            limits:
              memory: "20971520"
      restartPolicy: Always
status: {}
